ArdanaCLM/ardana-installer-ui

package.json

The information in package.json are outdated and should be updated
accordingly.

Update meta information in package.json

---

src/pages/ServerRoleSummary/NicMappingTab.js

Modify the logic that controls the Save button on the Nic Mapping tab of
the cloud settings dialog so that it is enabled only when the entries
are valid and when something has changed.  Previously the Save button
was enabled solely based on whether the data was valid, which led to it
being available even when nothing had changed, which may be slightly
confusing to the user.

NicMapping: Enable Save only when something has changed

---

src/components/Buttons.js
src/localization/bundles/en.json
src/pages/CloudModelSummary.js
src/styles/components/buttons.less
src/styles/components/messages.less

SCRD-2029 The main part of the bug was fixed in the ardana-input-model (https://gerrit.suse.provo.cloud/2267). This change only cleans up code and adjusts the look-and-feel of model card and info banner.

Clean up code and adjust some look-and-feel

---

src/pages/ServerRoleSummary/DiskModelDetails.js

SCRD-2241 The consumer attributes for a device group in the Disk Models tab of the Manage Cloud Settings modal was not able to accommodate different forms of consumer attributes because it was a text input field. Changed it to a textarea input field and added logic to handle the conversion between
yaml and javascript object.

Change consumer attributes field to text area

---

src/utils/InputValidators.js

Improve the validation of ip addresses in CIDR notation to reject those
addresses whose address portion is consistent with the leading bits.
Specifically, those bits after the leading bits must all be zeros.

Enforce numeric validation of CIDR values

---

src/pages/ServerRoleSummary/InterfaceModelsTab.js

Modify the logic that controls the Save button on the Inteface Models tab of
the cloud settings dialog so that it is enabled only when the entries
are valid and when something has changed.  Previously the Save button
was enabled solely based on whether the data was valid, which led to it
being available even when nothing had changed, which may be slightly
confusing to the user.

InterfaceModels: Enable save only when something has changed

---

src/pages/ServerRoleSummary/DiskModelDetails.js

SCRD-2483 Make Devices fields under Device Group in the Disk Models tab of the Manage Cloud Settings editable

Make Devices fields editable

---

src/localization/bundles/en.json
src/pages/AssignServerRoles.js
src/pages/AssignServerRoles/ConnectionCredsInfo.js
src/pages/AssignServerRoles/SmServerDetails.js

This checkin includes:
1. Passed the secured option to the call for getting servers and getting server
details.
2. Handled the situation when ipv6 table has empty entries for a server details.
3. Fixed to get ip address from non empty interface for a server.
4. Minor message fix.

Fixed issues related to suse manager integration

---

src/pages/ValidateConfigFiles.js
src/styles/components/ymlvalidator.less

Displays the config processor output when editing a yml file if the config processor failed validation

Show the log during file editing if validation failed

---

src/pages/ValidateConfigFiles.js

This checkin includes:
1. Fixed to have the backbutton enabled by default for config page
2. Fixed minor lints issues

Fixed issue for config page backbutton

---

src/components/Buttons.js
src/components/ServerRowItem.js
src/components/ServerTable.js
src/localization/bundles/en.json
src/pages/AssignServerRoles.js
src/styles/components/buttons.less

Requires: https://github.com/ArdanaCLM/ardana-installer-server/pull/15  in order to function correctly

Add ability to delete individual servers on assign server page

---

index.production

Change title from 'SUSE OpenStack Cloud Installer' to 'OpenStack Cloud Deployer' which is the same value as in the index.html file.

Remove SUSE reference from title (bsc#1082464)

---

src/styles/components/buttons.less

Reduced the opacity of the disabled button so it's more distinguishable from the active button.

Make disabled buttons a little lighter (bsc#1086378)

---

package.json
src/Deployer.js
src/InstallWizard.js
src/components/Buttons.js
src/components/Modals.js
src/localization/bundles/en.json
src/pages/CloudModelPicker.js
src/pages/Login.js
src/styles/common.less
src/utils/Auth.js
src/utils/RestUtils.js
src/utils/RouteUtils.js

Create modal dialog to prompt for credentials, and verify them against
keystone via the ardana-service.  Create functions and classes for
managing token information with cookies and injecting it into subsequent
REST calls.

Add keystone authorization UI

---

src/Deployer.js
src/components/NavMenu.js
src/localization/bundles/en.json
src/pages/Login.js
src/styles/branding.less
src/styles/common.less
src/styles/components/navmenu.less
src/styles/deployer.less
src/utils/RouteConfig.js

Create navigational menu system in the style of the EOS Design System [1].
Uses react-router to create a route to each of the main menu items and
sub-items.  This version supports only a fixed, static menu structure
in order to centralize the logic for routing and menu processing.
If we later need to perform dynamic routing (and dynamic menus), then
this can be introduced but may complicate the logic a bit.

SCRD-3458 Create menu system

---

src/pages/Login.js

When the user loads the application in secured mode and then logs in,
the menu system should be shown and the first main menu item, Services,
should be automatically selected.

Navigate to Service menu after login

---

src/components/Speedometer.js
src/localization/bundles/en.json
src/pages/SpeedometerTest.js
src/styles/components/speedometer.less
src/styles/deployer.less
src/styles/pages/SpeedometerTest.less
src/styles/palette.less
src/utils/RouteConfig.js

Create a speedemeter graph component that is modelled after the
"horseshoe" graph in the Operations Console.  Render the various SVG
components with a variety of configurable properties that enable
fine-tuning its appearance.  Create a test page for interactively
exercising the various properties of the speedometer.  Added the
test page into the prototype menu system.

SCRD-3483 Create speedometer graph component

---

src/localization/bundles/en.json
src/pages/AssignServerRoles.js

not ready to be merged, needs testing, needs an update to the description in the "Manage Subnet and Netmask" dialog to indicate which network those settings apply to

per training feedback, move manage cloud settings earlier, (bsc#1100445)

---

test/e2e/specs/sanitycheck.spec.js

Basically this fix will help the Selenium e2e sanity check script

SCRD-4476 Fix selenium test in ardana-installer-ui

---

package.json
src/pages/AssignServerRoles.js

add jquery back in for drag and drop highlighting to work

Restore drag and drop highlighting (bsc#1105119)

---

src/Deployer.js
src/InstallWizard.js
src/localization/bundles/en.json
src/pages/HtmlSummary.js
src/pages/topology/ControlPlanes.js
src/utils/RouteConfig.js

Add the control plane page into the topology section of the menu.  This
page is very close to the control plane page that is emitted by the
configuration processor.

Add control plane topology page

---

src/localization/bundles/en.json
src/pages/Login.js
src/styles/common.less

SCRD-4470 Updated Day2 Login page with guidelines from Cynthia. She recommended we use the SUSE Customer Center Login page as a template.

Update Day2 Login page per UX guidelines

---

src/localization/bundles/en.json
src/pages/ServiceInfo.js

If the endpoints API fails, pops up an error notification with a message that the service information is not available.

SCRD-4737 Add error handing when the API call fails

---

src/InstallWizard.js
src/components/EditServerDetails.js
src/components/ReplaceServerDetails.js
src/components/ServerRowItem.js
src/components/ServerTable.js
src/components/ServerUtils.js
src/localization/bundles/en.json
src/pages/AddServers.js
src/pages/ArdanaPackages.js
src/pages/AssignServerRoles.js
src/pages/BaseUpdateWizardPage.js
src/pages/OpenStackPackages.js
src/pages/ServiceInfo.js
src/pages/ServicesPerRole.js
src/pages/UpdateServers.js
src/styles/pages/AssignServerRoles.less
src/utils/ModelUtils.js
src/utils/RouteConfig.js

Merges changes from August 27th-Sept 4th into stable/pike from master

Merge sep042018

---

src/components/ServerUtils.js
src/localization/bundles/en.json
src/pages/ArdanaPackages.js
src/styles/common.less

Added filter box to the Ardana Packages page and updated the tab name and table name. The new tab name is 'SUSE OpenStack Cloud Packages' and the new table name is 'Installed Packages'.

SCRD-3478 Add search capabilty to Ardana Packages page

---

README.md
package.json
protractor.conf.js
src/InstallWizard.js
src/components/PlaybookProcess.js
src/pages/CloudDeployProgress.js
src/pages/ReplaceServer/InstallOS.js
src/pages/ReplaceServer/PrepareReplace.js
src/pages/SelectServersToProvision.js
src/utils/constants.js
test/e2e/specs/sanitycheck.spec.js

Change UI port from 3000 to 2209
Reference dayzero-* playbooks instead of installui-* playbooks

SCRD-3455 and SCRD-2228 Change port and remove dayzero names

---

src/pages/ServiceInfo.js

conform ServerInfo.js to new context menu props convention (handleShowModal->action)

SCRD-3497 - update service list menu to conform to menu refactor

---

src/components/InputLine.js
src/components/ListDropdown.js
src/pages/AssignServerRoles.js
src/pages/AssignServerRoles/ServersAddedManually.js
src/utils/ConfigHelper.js

Remove unnecessary state and convert to stateless functional components

Simplify components and convert to stateless functions

---

src/localization/bundles/en.json
src/pages/ReplaceServer/ReplaceController.js

Add additional steps to the replace server workflow for monasca
reconfiguration and osconfig playbooks.

SCRD-3497 Add monasca, os-config steps

---

src/InstallWizard.js
src/components/Buttons.js
src/components/ContextMenu.js
src/components/EditServerDetails.js
src/components/ModelServerDetails.js
src/components/ReplaceServerDetails.js
src/components/ServerRowItem.js
src/components/ServerUtils.js
src/components/SmServerDetails.js
src/components/ValidatingInput.js
src/pages/AddServers/CompleteAddServers.js
src/pages/AddServers/CompleteInstallOS.js
src/pages/AssignServerRoles/BaremetalSettings.js
src/pages/AssignServerRoles/ConnectionCredsInfo.js
src/pages/BaseUpdateWizardPage.js
src/pages/CloudModelPicker.js
src/pages/CloudModelSummary.js
src/pages/ReplaceServer/CompleteAddCompute.js
src/pages/ReplaceServer/DeployAddCompute.js
src/pages/ReplaceServer/PrepareAddCompute.js
src/pages/ServerRoleSummary.js
src/pages/ServerRoleSummary/UpdateNetworks.js

* Remove references to `this.props` from  component contructors
* Remove unnecessary constructors

SCRD-5564 Remove references to `this.props` in component constructors

---

src/components/PlaybookProcess.js
src/pages/AddServers/ProcessInstallOS.js
src/pages/CloudDeployProgress.js
src/pages/ServiceConfiguration.js

* Removed all uses of the old `extraVars` values

SCRD-5738 Switch to using `extra-vars` only

---

src/components/ValidatingInput.js
src/pages/ValidateConfigFiles.js
src/pages/ValidateConfigFiles/ServiceTemplatesTab.js

Removes deprecated componentWillReceiveProps life cycle callback.

SCRD-5562 remove componentWillReceiveProps hook

---

src/components/EditServerDetails.js
src/components/ReplaceServerDetails.js
src/pages/AssignServerRoles/BaremetalSettings.js
src/pages/ReplaceServer/DeployAddCompute.js
src/pages/ServerRoleSummary/DiskModelDetails.js
src/pages/ServerRoleSummary/ServerGroupDetails.js
src/pages/ServerRoleSummary/UpdateNetworks.js
src/utils/InputValidators.js

Refactor validators that use props to make decisions.

SCRD-5569 Refactor validators

---

package.json
pre-commit.sh
src/pages/ValidateConfigFiles.js

Add a pre-commit hook to make lint issues more surfaceable.

Add precommit hook

---

src/components/ValidatingInput.js
src/utils/InputValidators.js

Refactor validators to only return error messages on invalid.

SCRD-5727 Refactor validators to only return error

---

pre-commit.sh

* Fix issue that prevents committing files that are not js

Fix issue with pre-commit hook

---

src/InstallWizard.js
src/components/Graph.js
src/components/LoadingMask.js
src/pages/CloudModelSummary.js
src/pages/ServerRoleSummary/InterfaceModelsTab.js
src/pages/ServerRoleSummary/NicMappingTab.js
src/pages/ServerRoleSummary/UpdateNetworks.js
src/pages/ValidateConfigFiles.js
src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
src/pages/topology/ServerRoles.js
src/pages/topology/Servers.js

Resolves a lot of linter warnings

Replace ternary operators with If/Choose

---

src/pages/AssignServerRoles.js
src/utils/InputValidators.js

Restore support of immutable lists to the createExcludesValidator
function, which will reject as invalid any input that matches a list of
values.

SCRD-5569 Support immutable lists in excludes validator

---

package.json
src/pages/AssignServerRoles.js
src/utils/MiscUtils.js
yarn.lock

Reduces production bundle by 600k.

Remove jquery

---

package.json

Will need to update the node_modules tarball after this change as well

SCRD-5073 - update to newer version of react-bootstrap

---

src/styles/components/wizard.less

fixes the issue where the Day0 UI was constantly having a scrollbar. BS4 slightly changed the sizes of a few things, I just shrunk the margin on the footer to make it fit in the screen again

SCRD-5073 - fix vertical scrollbar issue introduced with bs4

---

src/utils/CsvImporter.js

The updated validators only return a value if there is an error. The csv importer was expecting values back. Updated the logic to match the new validators and csv import is working again

SCRD-5900 - update csv importer to work with new validators

---

src/components/EditServerDetails.js
src/components/Modals.js
src/pages/AssignServerRoles/ConnectionCredsInfo.js
src/pages/AssignServerRoles/ServersAddedManually.js

* Move password fields to forms
* Refactor touched classes away from class property syntax
* Use function bind syntax when needed

SCRD-5570 Move password fields to forms

---

src/components/LabeledInput.js
src/components/ValidatingInput.js

Remove redundant updateFormValidity call, this can be handled with inputAction call which often calls the same updateFormValidity method.

SCRD-5891 Remove redundant updateFormValidity call

---

src/Deployer.js
src/UpdateWizard.js
src/components/InlineAddRemoveFields.js
src/components/SmServerDetails.js
src/pages/AddServers.js
src/pages/AddServers/DeployAddServers.js
src/pages/AssignServerRoles.js
src/pages/CloudModelPicker.js
src/pages/CloudModelSummary.js
src/pages/Login.js
src/pages/ServiceConfiguration.js
src/pages/UpdateServers.js
src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
src/pages/topology/Networks.js
src/pages/topology/Servers.js
src/utils/Auth.js
src/utils/InputValidators.js
src/utils/MiscUtils.js
src/utils/ModelUtils.js
src/utils/RouteUtils.js

* Simplifies logic in many cases by replacing `&&` with `?.`

SCRD-5901 Use optional chaining when possible

---

src/pages/ServerRoleSummary.js

remove debugger statement that was accidentally left in

SCRD-3480 - remove extraneous debugger

---

src/components/EditServerDetails.js

* Prevent form submission to show server group and nic mapping modals
* resolve missing key prop warning

SCRD-6144 fix server group and nic mapping modals

---

src/pages/ReplaceServer/ReplaceController.js

Add the code to call the wipe disks playbook when the checkbox is
selected. Also remove debugging comments around code to power up server

SCRD-3497 Support wipe disks

---

src/pages/UpdateServers.js

* handle missing server in internal model, not sure how that happened to me
* Handle when state cannot be translated -> 'Unknown'
* Handle exception is thrown -> 'Unknown'

SCRD-5901 Fix some issues when fetching the monasca server status

---

src/localization/bundles/en.json
src/localization/bundles/en_branding.json
src/localization/bundles/ja_branding.json
src/pages/Complete.js

Get links for complete screen from the keystone catalog.

SCRD-6838, SCRD-4498 on complete show links

---

src/UpdateWizard.js
src/pages/UpdateServers.js

Because of props added to the page after an update wizard some items didn't get loaded properly.

SCRD-7374 properly load data on component mount

---

src/localization/bundles/en.json

replaced outdated number reference with section header per comments in SCRD-3498

SCRD-3498 - remove specific doc section number reference

---

src/components/Buttons.js
src/components/CollapsibleTable.js
src/localization/bundles/en.json
src/pages/ValidateConfigFiles.js
src/styles/components/buttons.less

- Remove selected border from picker-card
- Add tooltips to table actions
- Replace loading animation with eos-icon
- Wrap success message in an alert to add more visual feedback

SCRD-6923 Address UX/UI feedback

---

src/pages/Login.js
src/styles/components/buttons.less
src/styles/pages/login.less

Additional complexity was necessary as the guidelines used Bootstrap 3, and we are using Bootstrap 4.

Update button styling (SCRD-6923)

---

src/pages/ReplaceServer/InstanceMigrationMonitor.js
src/styles/components/migrationmonitor.less

* Use primary green color for progress bar
* Show spinner until 100%
* use black text color < 5% progress

Update styling on migration monitor progress

---

src/components/ReplaceServerDetails.js

Add server group/nic mapping buttonst to compute replace dialog.

Update replace details modal (SCRD-6822)

---

src/pages/ValidateConfigFiles.js

Update the layout of the yml editor to show same alert as config list.

Update layout of yml editor (SCRD-7642)

---

src/localization/bundles/en.json
src/pages/Complete.js

This won't fix the underlying issue but we should be handling errors here.

Add error message for links (SCRD-8302)

---

src/InstallWizard.js
src/localization/bundles/en.json
src/pages/CloudDeployProgress.js
src/pages/Complete.js

- Useful links could not be fetch if deployment finished and significant
time passed before navigating to the complete page. By fetching the
links during deployment this can be avoided.

Fetch useful links during deployment (SCRD-8302)

---

src/components/ServerRowItem.js
src/components/ServerTable.js
src/styles/common.less
src/styles/components/serverutils.less

Prevents server row highlights from being dragged as part of drag and drop.

Prevent drag of highlighted server text (SCRD-8585)

---

src/localization/bundles/en.json
src/pages/ServiceConfiguration.js
src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
src/styles/components/ymlvalidator.less
src/utils/MiscUtils.js
src/utils/constants.js

* Adds ability to upload ses_config.yml on configuration screens
* Adds required playbooks to reconfigure steps

Add SES integration into day0/2 (SOC-8555)
