- README.md
- run_dist.sh
Update the readme and run_dist.sh to properly reflect the fact that the
server layer has been extracted out into its own github repo:
ArdanaCLM/ardana-installer-server
> Update references to ardana-installer-server

- src/InstallWizard.js
- src/localization/bundles/en.json
- src/pages/AssignServerRoles.js
- src/pages/BaseWizardPage.js
- src/pages/CloudModelSummary.js
- src/styles/components/wizard.less
SCRD-2026 Show user-friendly name on subsequent pages after the user made a model selection. The name is showed in the upper right hand corner of the page.
Also includes a fix for a lints complaint in BaseWizardPage.js.
> Show user-friendly name of selected model after selection

- src/utils/ModelUtils.js
SCRD-2032 The entry-scale-kvm-ceph model uses both member-count and min-count in the clusters definition but the code only looks at member-count. I also found two other models that have min-count in their clusters definition: entry-scal-kvm-esx-vsa-mml (controller nodes) and entry-scale-kvm-vsa-mml (controller nodes).
> Add min-count to the processing of clusters

- src/pages/AssignServerRoles.js
On assign server role, current search text only filters on server name.
The fix is to include IP address or MAC address
> Fixed discovery search to include ip and mac address

- src/pages/ValidateConfigFiles.js
- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
On validate config files page, when user is in the edit mode, it hides the navigation buttons. User can switch tabs while the navigation buttons are hidden.
Fixed the issue by preventing user to go to different tab while edit file is open.
> Disable the other tabs when edit model file or service file

- src/components/Buttons.js
- src/components/Messages.js
- src/localization/bundles/en.json
- src/pages/AssignServerRoles.js
- src/pages/CloudModelPicker.js
- src/pages/CloudModelSummary.js
- src/pages/ServerRoleSummary/DiskModelsTab.js
- src/pages/ServerRoleSummary/InterfaceModelsTab.js
- src/pages/ServerRoleSummary/NetworksTab.js
- src/pages/ServerRoleSummary/NicMappingTab.js
- src/pages/ServerRoleSummary/ServerGroupsTab.js
- src/pages/ValidateConfigFiles.js
- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
- src/styles/common.less
- src/styles/components/buttons.less
- src/styles/components/messages.less
- src/styles/components/modelpicker.less
- src/styles/components/wizard.less
- src/styles/components/ymlvalidator.less
- src/styles/pages/AssignServerRoles.less
- src/styles/pages/ServerRoleSummary.less
Then changes include: 
1. When no model is selected, model selection details pane should say "No model selected"
2. When a model is selected, model selection details pane should include a title with the model name.  3. The selected checker button should have a check . 
4. When no component is selected, the component details pane should say "No component selected"
5. When a component is selected, the information describing it should be in an info box with an info icon, The selected checker button should have a check . 
6. The model assignment accordion should not have blank space below the final entry if that entry is not expanded 
7. Add <component> links in Manage Cloud settings should be clickable on the text and icon, not just the icon
8. Check icon in wizard progress bubbles should be …
> Fixed bugs based on UX feedback

- src/pages/CloudDeployProgress.js
'encrypt' is the proper extraVar to use, not 'encryptKey'.
A blank 'rekey' should be provided to avoid config-processor asking for this.
> Fix Encryption parameters

- src/localization/bundles/en.json
- src/pages/ServerRoleSummary/UpdateNetworks.js
- src/styles/pages/ServerRoleSummary.less
- src/utils/InputValidators.js
This checkin includes:
1. Added addresses input fields to add/update network
2. Added addresses validation to validate the list like:
1.1.2.2 - 1.1.2.3 or 1.1.2.34
Only validate the format, don't validate if the range is reasonable, or addresses are
within cidr.
3. Adjusted the styling for the network details section.
4. Added tooltip for cidr, vlanid and addresses to help user for network fields.
5. Mark the Server Group with * to indicate is required.
> Added addresses field to add/update network

- src/pages/AssignServerRoles/BaremetalSettings.js
The problem is that after a subnet or netmask change from the ManageSubnet and Netmask modal on the Assign Server page, you can click the back button to go to the Cloud Model Summary page but then you can't click the Next button to come back to the Assign Server page again. This change fixes that behavior.
> Fix progress back and forth after changing subnet or netmask

- README.md
- build_dist.sh
- build_ui.sh
Juggle the npm install around so that build_ui.sh can be called directly
in the OBS .spec file to perform a build.  Update README for
instructions on building the node modules tarball.
> Facilitate OBS builds

- src/localization/bundles/en.json
- src/pages/ServerRoleSummary.js
- src/pages/ServerRoleSummary/DiskModelDetails.js
- src/pages/ServerRoleSummary/DiskModelsTab.js
- src/pages/ServerRoleSummary/EditCloudSettings.js
- src/pages/ServerRoleSummary/InterfaceModelsTab.js
- src/pages/ServerRoleSummary/NetworksTab.js
- src/pages/ServerRoleSummary/NicMappingTab.js
- src/pages/ServerRoleSummary/ServerGroupDetails.js
- src/pages/ServerRoleSummary/ServerGroupsTab.js
- src/pages/ServerRoleSummary/UpdateNetworks.js
- src/styles/pages/ServerRoleSummary.less
SCRD-1950 Add a confirmation modal before exiting the Manage Cloud Settings modal when detecting changes to any of the tabs so that the user won't lose the changes accidentally. 
Also fix the logic to detect changes in the Networks tab which didn't compare the new value with the original value which caused the tab to report a change even when the new value and the original value are the same.
The change in ServerRoleSummary.js is an enhancement to expand the first group when there's no COMPUTE-ROLE group. An example of this case can be seen when you selected Entry Scale Ironic Multi-tenant Network.
> Ask for confirmation before exiting Manage Cloud Settings modal

- src/localization/bundles/en.json
- src/pages/ServerRoleSummary/InterfaceModelsTab.js
SCRD-2403 Add Forced Network Groups area to the Interface Models tab in the Manage Cloud Settings modal. You can see forced network groups in eth0 interface under ESX-COMPUTE-INTERFACES or OVSVAPP-INTERFACES of the Entry Scale ESX KVM VSA template.
> Add Forced Network Groups to Interface Models

- src/components/Buttons.js
- src/components/EditServerDetails.js
- src/components/ServerUtils.js
- src/pages/AssignServerRoles.js
- src/pages/ServerRoleSummary.js
- src/pages/ServerRoleSummary/CollapsibleTable.js
- src/pages/ServerRoleSummary/EditCloudSettings.js
- src/styles/components/buttons.less
- src/styles/components/serverutils.less
SCRD-2394 Add two new buttons to the Edit Server Details modal to allow the user to add new nic mappings or server groups. The buttons launch the Manage Cloud Setting modal with only one tab, either the Nic Mappings tab or the Server Groups tab.
Also change the Manage Cloud Settings and the Manage Subnet and Netmask buttons to be just default buttons (gray color).
> Add ability to add new nic mappings or server groups from Edit Server Details modal

- src/pages/ServerRoleSummary/UpdateNetworks.js
- src/styles/pages/ServerRoleSummary.less
This checkin fixed the issue where network addresses input plus/minuse
styling 100% overwrote styling 85% in other places for example, in Disk
Models tab, Add Volume Group when add physical volumes.
> Fixed input with plus and minuse overwritten issue

- src/components/InlineAddRemoveFields.js
- src/localization/bundles/en.json
- src/pages/ServerRoleSummary/CloudConfigTab.js
- src/pages/ServerRoleSummary/DiskModelDetails.js
- src/pages/ServerRoleSummary/DiskModelsTab.js
- src/pages/ServerRoleSummary/EditCloudSettings.js
- src/pages/ServerRoleSummary/InterfaceModelsTab.js
- src/pages/ServerRoleSummary/NetworksTab.js
- src/pages/ServerRoleSummary/NicMappingTab.js
- src/pages/ServerRoleSummary/ServerGroupDetails.js
- src/pages/ServerRoleSummary/ServerGroupsTab.js
- src/pages/ServerRoleSummary/UpdateNetworks.js
- src/styles/pages/ServerRoleSummary.less
SCRD-2410  We added a new tab "Cloud Configuration" to the Manage Cloud Settings modal to allow the user to provide the NTP and DNS settings. The user can update the Host Name Prefix and Host Member Prefix values on this tab as well. 
This UI change also contains the resetting of data changes in each tab every time the modal is closed. This is to keep track of changes correctly, otherwise when the modal is launched again and even no change was made, the modal might still think that there're changes and keeps popping up the confirmation modal when the user wants to exit.
> Add ability to edit NTP and DNS settings

- src/components/Messages.js
- src/localization/bundles/en.json
- src/pages/CloudDeployProgress.js
- src/pages/SelectServersToProvision.js
- src/styles/components/messages.less
- src/styles/components/serverprovision.less
- src/styles/palette.less
SCRD-2320 Added an error banner to the OS install page and the cloud deploy to inform the user of the next steps they could do when there's a failure in the process. 
I tested by changing the updatePageStatus function on each page to set this.state.overallStatus value to STATUS.FAILED to simulate a failure in the process.
> Add guidance when OS install or cloud deploy fails

- src/pages/ServerRoleSummary/InterfaceModelsTab.js
SCRD-2482 Fixed the behavior of the Network Devices dropdown in Interface Model tab of the Manage Cloud Settings modal, which was not updating the value correctly in the edit mode.
> Fix Interface Model's Network Devices dropdown

- src/components/PlaybookProcess.js
- src/pages/CloudDeployProgress.js
This checkin includes:
1. Fixed the status problem where the status was not updated correctly
when there are some playbooks included in step but acutally they might
not get run based on user settings,  for example monasca playbooks.
2. Also added a condition where to detect only need one playbook gets run
to decide if the step completes. For example site.yml or dayzero-site.yml.
3. Updated to have ardana-status.yml for the health step
> Fixed the status problem for cloud deploy process

- index.html
- src/InstallWizard.js
This checkin fixes the problem where the tab title doesn't pick up
the branding title.
Also updated the default tab title to align with the actual title
> Updated document.title to use the branding title

- src/localization/bundles/en.json
- src/pages/CloudModelPicker.js
- src/styles/components/modelpicker.less
SCRD-2470 Added a confirmation modal when user selected a different cloud model than before. This is a generic warning to the user and does not actually keep track of any change that may happen after the user selected a cloud model for the first time.
> Add confirmation modal when changing cloud model

- src/components/Buttons.js
- src/localization/bundles/en.json
- src/pages/AssignServerRoles.js
Updated buttons on Auto Discover and Manual Entry tabs on the Assign Server Roles page from primary button (green color) and link to default button (gray color). These are buttons that show up at the search bar area after some servers were discovered or added manually.
> Update buttons on Assign Server Roles page to default

- src/localization/bundles/en.json
- src/pages/CloudModelPicker.js
SCRD-2470 After the user selected a different input model than what they selected before and said no to the confirmation modal, the selected value will be set back to the previously selected value.
> Set selected model to previously selected value after user says no

- package.json
- src/pages/CloudModelPicker.js
SCRD-2193 The input model team no longer provides README.html files, but only README.md files. Added Showdown and used it to convert .md files back to html format in order to display the template descriptions again.
Depends on this ardana-service change: https://gerrit.suse.provo.cloud/#/c/3178
> Add Showdown library to convert .md to .html

- src/components/PlaybookProcess.js
- src/styles/components/playbookprogress.less
- src/styles/components/wizard.less
- src/styles/components/ymlvalidator.less
- src/styles/palette.less
Bugzilla 1078351 - Changed from using the blueish green color to the main green color in 3 places:
1. in-progress icon on deploy step bar - I think we used the blueish green color to differentiate the in-progress step from the previous done steps. Now that we indicated the done steps with a check mark icon, the color of in-progress and done steps can be the same.
2. cloud deploy progress text for done state on Cloud Deployment Progress page - switched to use the main green color and added a check mark icon at the end
3. validated icon on Review Configuration Files page
> Switch from using blueish green color to main green color 

- src/localization/bundles/en.json
- src/pages/CloudModelSummary.js
- src/styles/components/modelpicker.less
Bugzilla 1080184 - added an info banner on the Cloud Model Summary page when user selects a mandatory component that has 3 nodes
> Add guidance on changing number of nodes

- index.html
Bugzilla 1082464 - replaced "SUSE OpenStack Cloud Deployer" with "OpenStack Cloud Deployer" in the page title
> Remove SUSE from default page title

- src/localization/bundles/en.json
- src/pages/CloudModelPicker.js
If the user has selected a model and progressed through the installer
and changed then name on the page that permits model editing and then
returned back to the model selection page, display (and automatically
select) a new "custom" box that reflects this change.  This permits the
user to go forward again without forcing a selection of an existing
template and overwriting their customized changes to the model.
> Handle custom model names in selection page (bsc#1082586)

- src/components/ServerTable.js
- src/localization/bundles/en.json
- src/pages/AssignServerRoles.js
- src/pages/AssignServerRoles/ModelServerDetails.js
- src/pages/AssignServerRoles/ServersAddedManually.js
- src/pages/AssignServerRoles/ViewServerDetails.js
- src/pages/CloudModelSummary.js
- src/pages/ServerRoleSummary/CollapsibleTable.js
- src/styles/components/buttons.less
- src/styles/components/serverutils.less
- src/styles/pages/AssignServerRoles.less
- src/utils/CsvImporter.js
Added the Edit Server modal for servers added manually. The work includes refactoring out the existing code that handles servers added manually to be it's own module and reusing it for the edit modal.
Also fixed the View Details modal so that it's look and feel is consistent with the Add and Edit modals.
The changes in CloudModalSummary and CsvImporter are fixes for lints complaints.
> Add Edit Server modal for servers added manually (bsc#1080193)

- src/pages/CloudModelPicker.js
The propsModelName variable used to return an undefined but now returns a null. This causes the warning modal to come up when the template was selected for the first time which is not a correct behavior. Changed from '===' to '==' which takes the null value into account in that check.
> Fix warning modal when select template for the first time (bsc#1082902)

- src/localization/bundles/en.json
- src/pages/Complete.js
The current code shows the shutdown instruction only when the user name is available. This can be a problem when the user name is not retrievable. Added code to show a generic shutdown instruction when the user name is not available.Also switched to use the get user call from the shim layer instead of the ardana service.
This change depends on the change to add the get user call to the shim layer: https://github.com/ArdanaCLM/ardana-installer-server/pull/22
> Add showing of shutdown instruction even with no user (bsc#1078354)

- src/InstallWizard.js
- src/localization/localize.js
- src/pages/Complete.js
The root cause of the problem is that the get model call failed at the Complete page. This causes the progress step to get set back to the default value of 0. This fix makes sure that get progress is called whether the get model call is successful or not.
Also if the model name can't be retrieved, do not display the first two lines which show the model name.
> Fix UI go to first page when model is not retrievable (bsc#1084377)

- src/components/PlaybookProcess.js
- src/pages/ServerRoleSummary/DiskModelsTab.js
- src/pages/ServerRoleSummary/InterfaceModelsTab.js
- src/pages/ServerRoleSummary/NicMappingTab.js
- src/pages/ServerRoleSummary/ServerGroupsTab.js
- src/styles/pages/ServerRoleSummary.less
SCRD-1663 Added tooltips to the number values in the table which showed the item names so the user could see the names easily without having to use the Edit function. The changes were made for the following tabs: NIC Mappings, Server Groups, Disk Models, and Interface Models
Also fixed a lint complaint in PlaybookProcess.js
> Add tooltips to Manage Cloud Settings tabs

- src/pages/ServerRoleSummary/InterfaceModelsTab.js
Fixed an issue with Forced Network Groups which caused by incomplete validation logic when the user add/update a Network Interface of an Interface Model in the Interface Models tab of the Manage Cloud Setting modal.
> Fix issue with Forced Network Groups (bsc#1087967)

- src/localization/bundles/en.json
- src/pages/CloudDeployProgress.js
- src/pages/ValidateConfigFiles.js
- src/styles/components/ymlvalidator.less
SCRD-2198 Added the 'Clear Unused Servers/Addresses' checkbox to the Deployment tab of the Review Configuration Files page, to allow users to clear out unused IPs
Note: when testing, please run the UI with reset=true option to make sure that the deploy configuration is initialized properly
> Add option to clear out unused IPs

- src/Deployer.js
- src/localization/bundles/en_branding.json
- src/localization/bundles/ja_branding.json
Just one possible approach to routing for the Day2 UI... when the app is up and running add a '#/about' or '#/login' to the end of the URL to see the alternate routes... this can lead to some weird urls when resetting things...  such as 'http://localhost:8081?reset=true/#/'
hold off merging this until we have a chance to discuss it and look at alternatives
> WIP: one possible routing solution

- src/Deployer.js
- src/InstallWizard.js
- src/utils/Auth.js
Perform a check at the application load, before rendering the
InstallWizard, to verify whether a login screen should be displayed
instead.  Display a loading screen while this check is being made.  This
avoids temporarily showing the Install Wizard and then immediately
jumping to the login page.
Move REST calls from the InstallWizard's constructor into its
componentDidMount per ReactJS guidelines [1].  The InstallWizard may be
constructed by its parent (in Deployer.js) before deciding whether to
actually render it, so moving these REST calls to the constructor
permits the Deployer to properly avoid rendering the InstallWizard (and
avoid its REST calls) until it decides that it should.  This change
is also needed by the day 2 scenarios where the InstallWizard should not
automatically be …
> Avoid unnecessary hop at startup in secured mode

- src/utils/CsvImporter.js
Fixing CsvImporter.js to allow server_id as a valid column name for importing server id.
> SCRD-3672 Fix id alias server-id in field_defs

- lib/fonts/fontawesome-webfont.eot
- lib/fonts/fontawesome-webfont.svg
- lib/fonts/fontawesome-webfont.ttf
- lib/fonts/fontawesome-webfont.woff
- lib/fonts/fontawesome-webfont.woff2
Remove the links residing in /lib/fonts that refer to fontawesome fonts
in /thirdparty/fonts that were recently removed.
> SCRD-1994 Remove dangling symlinks

- src/pages/Login.js
When the login screen is shown, automatically move the focus to the
first field, username, to facilitate typing credentials.
> Auto focus on username field on login screen

- src/Deployer.js
- src/pages/Login.js
- src/utils/RouteUtils.js
Normally the UI decides whether to display the menu or the installer wizard depending on whether authentication is required: If authenticating, then go to the menu (after logging in); else display the installer. Add support for the query parameter ?start=menu or ?start=installer in order to control which screen is initially displayed. This is clearly meant for developers. 
In the event that an end user discovers this feature and uses it, there is really no down-side other than some possible confusion -- all secured endpoints are still enforced on the REST service end.
> Support for explicitly controlling navigation

- src/localization/bundles/en.json
- src/pages/ServicesPerRole.js
- src/styles/common.less
- src/utils/RouteConfig.js
SCRD-3488 Added 'Service Per Role' which is the page under a new tab called 'Roles' off of the Services menu. The page contains three columns: Roles, Servers, and Services. The Servers column shows host IDs instead of host names at the moment. The plan is to show host names when we can get them from the output of the config processor run which will come later on.
> Add Services Per Role page

- src/components/NavMenu.js
- src/localization/bundles/en.json
- src/pages/Login.js
- src/pages/ServiceInfo.js
- src/pages/ServicesPerRole.js
- src/styles/common.less
- src/utils/RouteConfig.js
SCRD-3484 Added 'Service Information' page which is the page under the 'Information' tab off of the Services menu. The page contains a table with four columns: Name, Description, Endpoints, and Regions. There's supposed to be the fifth column which is the 'Status' column, but we need the status data from Monasca which is not available at the moment. Once the Monasca data is available, we will need to add the Status column to the table.
Also updated how the navigation menu works by getting rid of the landing page and setting the first tab of each menu to be the default page when the menu was selected.
> Add Service Information page

- src/components/CollapsibleTable.js
- src/components/NavMenu.js
- src/utils/ConfigHelper.js
- src/utils/RouteConfig.js
Hides examples, navigation items, and menu items that aren't finished yet from the user when in production mode.
> Hide unfinished functionality in the Day2 UI (bsc#1105689)

- src/components/Buttons.js
- src/components/Modals.js
- src/components/PlaybookProcess.js
- src/localization/bundles/en.json
- src/pages/ServiceInfo.js
- src/pages/ServicesPerRole.js
- src/styles/components/contextmenu.less
- src/styles/components/playbookprogress.less
SCRD-3485 Added a drop down menu that contained 'Details' and 'Run Status Playbook' actions for each service in the Service Information page. Then implemented the modal dialog that showed the streaming of result from running status playbook for the selected service. The Details menu doesn't do anything at the moment.
> Add Run Status Playbook action for services

- package.json
- src/pages/topology/ControlPlanes.js
- src/pages/topology/Regions.js
- src/pages/topology/TopologyUtils.js
- src/utils/RouteConfig.js
Add region page in the topology section.  Introduce caching so that
toggling between topology tabs does not cause a re-load.  Use
componentDidMount instead of componentWillMount for loading data
per the guidance in the react documents:
https://reactjs.org/docs/react-component.html#componentdidmount .
Enable linking to anchors on different pages.
> Add region topology page

- src/localization/bundles/en.json
- src/pages/ArdanaPackages.js
- src/pages/OpenStackPackages.js
- src/utils/RouteConfig.js
SCRD-4309 Added two new pages under the Services menu: OpenStack Packages page and SUSE Cloud Packages page (for Ardana packages)
To test, you can point your shimurl in config.dev.js to Jack's machine at http://192.168.200.88:3000. I'm not sure what's the official name for Ardana is, so I'm using 'SUSE Cloud' for now. I can update if if/when we decide to use a different name.
> Add OpenStack Packages and SUSE Cloud Packages pages

- src/localization/bundles/en.json
- src/pages/ServicesPerRole.js
Updated the Servers column in Services Per Role page to use the combination of server names and server IDs instead of just server IDs. In order to get the server names, I had to switch to get the data from the output model instead of the input model. Also added error handling and loading mask.
> SCRD-4430 Update Servers column in Services Per Role page

- src/localization/bundles/en.json
- src/pages/topology/ControlPlanes.js
- src/pages/topology/Networks.js
- src/pages/topology/Regions.js
- src/pages/topology/ServerGroups.js
- src/pages/topology/Services.js
- src/styles/common.less
- src/styles/pages/Topology.less
- src/utils/RouteConfig.js
Add servers tab to the topology page.
Implement styling changes to clarify relationships, making the pages
more similar to the original versions from the config processor.
> Add servers topology tab

- src/pages/ArdanaPackages.js
- src/pages/OpenStackPackages.js
Updated the OpenStack Packages page and the SUSE OpenStack Cloud Packages page with the new API. This change depends on these backend changes which implement the new API: https://gerrit.suse.provo.cloud/#/c/4708 and https://gerrit.suse.provo.cloud/#/c/4709. Please do not merge this change until the backend changes were merged.
> SCRD-3478 Update OpenStack and Ardana Packages pages with new API

- src/pages/ServiceInfo.js
Map the following services to the right playbook: 
1. Ardana --> ardana-service-status.yml
2. Cinderv2 and Cinderv3 --> cinder-status.yml
3. Kronos --> logging-status.yml
4. Opsconsole -> ops-console-status.yml
> SCRD-5069 Correctly map status playbook for some services

- src/pages/CloudDeployProgress.js
- src/pages/ReplaceServer/InstallOS.js
- src/pages/ReplaceServer/PrepareReplace.js
- src/pages/SelectServersToProvision.js
- src/utils/constants.js
The merge-revert of the original constants change at https://github.com/ArdanaCLM/ardana-installer-ui/pull/146  was incorrect and should have included the constants changes to put the playbook names into the constants file.
This change rectifies that by redoing those parts of #146 on stable/pike
> SCRD-3455 - implement constants changes in stable/pike

- src/pages/topology/ServerRoles.js
Improve layout when disk model table has fewer rows than interface model
table.  Change the title of one of the columns from Sizesize to Size.
> Improve server role topology layout

- src/pages/ServiceInfo.js
Adjusted loading mask on Day2 UI's Service Info page when monasca service is not available (most likely in development environment) so that it doesn't look like the page is loading forever. The loading mask now only depends on the api to retrieve endpoints, which is enough to render the table.
> SCRD-5194 Adjust loading mask on Service Info page

- src/components/Modals.js
- src/localization/bundles/en.json
- src/pages/Login.js
Added a new error message on the Login page and the login modal for the scenario that the ardana service cannot connect to keystone. This change depends on the ardana-service change https://gerrit.suse.provo.cloud/4843, which was merged into master on 10/03/2018. 
To test this in dev environment, you can shut down your keystone docker container with this command: docker stop <containerID>. Once you're done testing, you can bring back your keystone container with this command: docker start <containerID>.
> SCRD-4431 Add error message for keystone unavailable case

- src/InstallWizard.js
- src/components/WizardProgress.js
- src/styles/components/wizard.less
The install wizard has an "update" mode that should be contained
as much as possible to the functioning of the wizard itself.  Removed
the code to pass along this mode flag to WizardProgress and used CSS
alone to do the styling.
> Reduce scope of update mode

- src/components/PlaybookProcess.js
- src/utils/MiscUtils.js
This change is to fix the problem of running status playbook does not display the last few lines of the log due to the fact that the socket connection was severed right away. Added a 2-second wait time in the process to wait for the 'end tag' to arrive which should be plenty for the last few lines of the log to show up.
> SCRD-3485 Add wait time to run status playbook

- src/components/CollapsibleTable.js
- src/components/ReplaceServerDetails.js
- src/localization/bundles/en.json
- src/utils/InputValidators.js
The field validation in the replace server dialog had three problems:
- It did not exclude in-use servers from the pulldown list of
available servers.
- The duplicate check should have flagged only those values used in
a server in the model
- The duplicate IP address check should have checked against IP
addresses used either as the main server address or its ILO address
In the process of improving the parameters to the validator I found
that the existing mechanism of checking for duplicates required very
tight coupling between the validator function and the field being
validated: specifically, the validator required that the input be
passed with two hardcoded properties, each of which needed to contain
a very specific structure.  Rather than propagating that further,
established a more …
> SCRD-3497 Fix field validation in replace server dialog

- src/localization/bundles/en.json
- src/pages/ServiceConfiguration.js
- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
- src/styles/common.less
Added the update functionality to the 'Update' button on the page. Note that when I tested in mock mode, the update ran all the way through. But when I tested with Oak's backend, the log message area showed messages of the update process until it hit the 'stop haproxy' command, then stopped showing any more messages. The update process however still proceeded in the backend. This issue can be solved in a separate pull request.
> SCRD-3489 Add Update Service Config - Part 2

- src/components/CollapsibleTable.js
- src/components/Modals.js
- src/components/PlaybookProcess.js
- src/localization/bundles/en.json
- src/pages/ServiceInfo.js
- src/styles/components/modals.less
Added "Provide SSH Passphrase" modal to the run status playbook step so that the user can provide their passphrase to be used to run the playbook. This hopefully will be a pattern that other run playbook steps can use when the passphrase is required. 
Oak and Dogwood in their current states do not have the ssh passphrase setup. The following steps set up the ssh process to require a passphrase:
1. back up the original id_rsa and id_rsa.pub files on the deployer
2. run 'ssh-keygen'  then provide a passphrase, this will create the new id_rsa and id_rsa.pub files
3. restart the ardana service
At this point the system will require a passphrase when you run any playbook (the 'requires_password' API will return 'true'). Once the passphrase is provided, it will be automatically used in all …
> SCRD-4240 Add passphrase modal to run status playbook

- src/localization/bundles/en.json
- src/pages/ServiceConfiguration.js
- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
Added updating steps that are driven by the number of services being updated. If updating config files for one service, runs the service -reconfigure.yml and -status.yml. If updating config files for more than one service, only runs ardana-reconfigure.yml (which calls ardana-status.yml at the end).
Tested on Dogwood but I had to temporary change the PRE_DEPLOYMENT_PLAYBOOK in constants.js to 'dayzero-pre-deployment' because installui-pre-deployment did not exist yet.
> SCRD-3489 Update Service Config - Part 3

- src/localization/bundles/en.json
- src/pages/UpdateServers.js
Detect the situation where the controller that has been requested to be
replaced is also hosting the deployer, and prompt the user to perform
this manually.  Replacing a shared node is far more complex and is not
included in this user story.
>  SCRD-3497 Disallow replacing shared controller/deployer

- src/components/PlaybookProcess.js
- src/pages/ReplaceServer/PrepareReplace.js
Add support for supplying an arbitrary action instead of only launching
ansible playbooks. The action is a function that returns a promise,
which enables it to be used for making API calls to the back end as well
as any other call.
Replaced logic that used isUpdateMode to indicate that the playbook
array was to contain objects (instead of just names) with logic that
inspected the array and made the decision based on the contents.
Added documentation for the props passed in to PlaybookProcess.
Added an example function in PrepareReplace.
> SCRD-3497 Support running non-playbooks with PlaybookProgress

- src/localization/bundles/en.json
- src/pages/ReplaceServer/PrepareCompute.js
- src/pages/ReplaceServer/PrepareController.js
- src/pages/ReplaceServer/UpdateServerPages.js
- src/pages/UpdateServers.js
Add a new page for the prepare server workflow that is specifically for
preparing control nodes for replacement, up to the point where the OS
installation would begin.  Moved the model commit into an action so that
it will not be repeated when the page is realoaded.
Moved PrepareReplace to PrepareCompute, since the workflow for replacing
a compute node is different.
> SCRD-3497 Add PrepareController

- src/components/PlaybookProcess.js
- src/pages/ReplaceServer/PrepareController.js
- src/pages/UpdateServers.js
Replace call to cobbler deploy with a call to the
install-ui-os-provision playbook, which is also used by the install
wizard.
Support defaulting and passing extra-vars in both install and update
scenarios.
>  SCRD-3497 Use install os provision playbook

- src/localization/bundles/en.json
- src/pages/ReplaceServer/ReplaceController.js
If the server being replaced is the swift ring builder, there are some
steps that are currently required to be performed manually part of the
way through the process.  Added logic to determine this situation.
Added promise-handling logic to be able to interrupt the flow of the
replacement while waiting for the user to complete the manual steps.
Invoke the ardana-deploy playbook with the appropriate host limit,
depending on whether the node is a swift ring builder.
> SCRD-3497 Handle swift ring builder, ardana-deploy

- src/components/ValidatingInput.js
- src/pages/AssignServerRoles/ConnectionCredsInfo.js
Instead of tracking the inputValue in both the internal state as well as
the props, rely on the parent to update the props whenever the user
changes the value, which is done via the inputAction callback.  This
matches the more standard reactJS model and fixes spurious problems
seen when updating the control programatically.
> SCRD-5562 Stop tracking inputValue in internal state

- src/pages/ReplaceServer/ReplaceController.js
When calling the install playbook, the extra-vars should contain a node
list.  The node list should always be a simple string, rather than a
python list.  Note that in the event that multiple nodes are to be
supplied (not relevant in this change), the string should be a
comma-separated list of nodes.
> SCRD-3497 Avoid passing list in extra vars

- src/components/CollapsibleTable.js
- src/components/ContextMenu.js
- src/components/Modals.js
- src/localization/bundles/en.json
- src/pages/UpdateServers.js
There is still an issue with this. If the use is quick enough it is possible that the context menu will have no activate or deactivate option because the status is still loading from the backend.
> SCRD-3479 Add activate/deactivate to server management for compute hosts

- src/styles/common.less
When the font Arial is not available some browsers will fall back to a serif/TimesNewRoman looking font which does not look similar to Arial at all.
> SCRD-5901 Add fallback font for when 'Arial' is not available

- src/pages/AddServers/DeployAddServers.js
- src/pages/ReplaceServer/DisableComputeServiceNetwork.js
- src/pages/topology/TopologyUtils.js
Loading the model that is output from the config processor, a.k.a., the
internal model, was potentially quite slow (up to about 10 seconds), so
the getInternalModel function was originally created in order to avoid
even re-querying the back-end, making the UI much faster.  But that
solution incorrectly served up old results after the config processor
was run again.  So some pages were bypassing getInternalModel and
performing the fetch directly and explicitly adding 'cache-control:
no-cache' in order to forcably re-load fresh results, and other pages
were not.
Re-factor the code to always use the no-cache header when reading the
internal model.  Note that the no-cache option has a misleading name,
since it actually compares the cached response with the ETag from the
server and only …
> SCRD-3111 Use smarter caching of internal model

- src/InstallWizard.js
- src/pages/CloudModelPicker.js
- src/pages/CloudModelSummary.js
- src/pages/UpdateServers.js
The step to commit the model did not first wait for the model to be
saved, and if the commit happened first, then uncommitted changes would
result, causing the replace controller flow to terminate.  Modify the
updateGlobalState function to return a promise that is resolved when
the save is complete, so that the following functions can be
synchronized properly.
> SCRD-3497 Avoid race condition with model save and commit

- src/components/CollapsibleTable.js
- src/pages/UpdateServers.js
The collapsible table had a magic number that was incorrect calculating the number of columns to display. Fixed that issue and leveraged the fix to hide the Monsaca column when Monasca is not installed
> SCRD-3481 - only show Monasca column when Monasca is installed

- src/InstallWizard.js
- src/pages/AddServers.js
- src/pages/AssignServerRoles.js
- src/pages/ReplaceServer/ReplaceController.js
- src/styles/common.less
- src/styles/components/logviewer.less
- src/styles/components/playbookprogress.less
- src/styles/components/serverprovision.less
- src/styles/components/wizard.less
Adjust layout of screens when running playbooks.  Both day 0 and day 2
re-use some of the same components, but since they have different sized
headers at the top of the screen, some of the calculations have to
adjust for these differences.
> SCRD-6669 Adjust layout when running playbooks

- pre-commit.sh
Prior to this change it is not possible to commit a file rename,
eslint is told to check a file that does not exist anymore
> Update precommit hook to handle renames

- src/Deployer.js
- src/InstallWizard.js
- src/components/NavMenu.js
Currently the title switches from "SUSE OpenStack Cloud" to "CLM Admin UI" when the user logs in, and if they navigate to the `Servers` page, it becomes "SUSE OpenStack Cloud Installer" , which makes no sense at all
> SCRD-5795 - fix browser tab title for Day2 UI

- src/components/Modals.js
- src/localization/bundles/en.json
- src/pages/Login.js
- src/pages/ServiceInfo.js
At the login prompt add a modal dialog to prompt for the SSH passphrase
if one is needed in order to load the private SSH key.  Improve the
text to explain how it is used and how to deal with restarts while
logged in.  Remove the ability to close the dialog without entering
a valid passphrase. Remove the ssh password dialog from the ServiceInfo
page.
> SCRD-4240 Add passphrase dialog to login page

- src/pages/ReplaceServer/ReplaceController.js
In order to modify ~/.ssh/known_hosts properly, use the new
ardana-ssh-keyscan.yml playbook created for this purpose.
> SCRD-6607 Use ardana-ssh-keyscan playbook

- src/pages/AssignServerRoles.js
When servers didn't have a uid property drag and drop will assign all servers to the role a server was dropped onto.
> SCRD-5901 Fix issue where role DnD moved all servers

- src/pages/Complete.js
Will avoid error if connecting to the old back end.
> Avoid error when linkName property is null

- src/components/Modals.js
Change the nesting of the error message so that it appears in front of
the ssh passphrase dialog rather than behind it.
> SCRD-4240 Improve reporting of ssh passphrase errors

- src/pages/AssignServerRoles/ConnectionCredsInfo.js
Port input had "host" as its name, which was causing changes to the port to appear in the host field
> Fix port input to model mapping in discover model (SCRD-6488)

- src/pages/AssignServerRoles.js
The servers can still be dragged and dropped, this stops the tab elements themselves from being dragged.
> Prevent tabs from being dragged to server dropzone (SCRD-6668)

- src/components/PlaybookProgress.js
- src/pages/ServiceConfiguration.js
- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
Remove cancel from the playbook progress page for service reconfiguration (i.e. the page where the update has been kicked off and is running).
When cancel is clicked on the Configuration tab (when configuration files have been edited but no updated launched), reload the playbooks in addition to resetting their updated status
> Fix cancel/revert issues with service reconfigure (SCRD-5880)

- src/components/HelpText.js
prevents the "tooltip flash" on certain pages. Does mean that tooltip placement is now dynamic and will not default to the same position for everything, but seems a reasonable tradeoff.
> Change tooltip placement to auto (SCRD-7643)

- src/pages/ValidateConfigFiles/ServiceTemplatesTab.js
- src/styles/components/ymlvalidator.less
The click listeners in the "configuration" page of the service list are conflicting due to the buttons for the services overflowing the container they're in.
changed buttons to anchors
increased line-height of the service links
tweaked margin around the list items
> Fix click listener collision on service list (SCRD-7644)

- src/pages/Login.js
- src/utils/RouteUtils.js
The logic to "goBack" to the page that timed out isn't working and causes the user to have to login twice (only to be taken to the default landing page anyway). For now, removed the extra logic, which fixes the double login problem.
> Remove broken goback logic when token expires (SCRD-5747)

- src/InstallWizard.js
- src/pages/UpdateServers.js
- Wait for model to be loaded before fetching server statuses.
- If there is a pending promise to load the model, return that promise.
Can potentially dedupe simultaneous requests.
> Load the model before service statuses (SCRD-8483)

- src/localization/bundles/en.json
- src/pages/ModelConfiguration.js
- src/pages/ValidateConfigFiles.js
The model tab under "services" in the Day 2 UI does not automatically deploy updates to the cloud, though users can make, commit, and validate changes there. Added clarifying text in the Day2 scenario (Day0 is unchanged)
> Clarify Day2 Model changes are not deployed automatically (SCRD-8694)

- src/InstallWizard.js
- src/localization/bundles/en.json
- src/pages/CloudDeployProgress.js
If the deployment page was refreshed the useful links in state
could be lost. Persisting them fixes this.
> Make useful links persist (SCRD-8302)

- src/localization/bundles/en.json
- src/pages/Complete.js
Instead of going to the general SUSE documentation page the link should
point to the SUSE OpenStack Cloud 9 documentation page
> Update documentation useful link (SCRD-8689)
